- name: SELinuxの状態確認
  command:
    /usr/sbin/selinuxenabled
  register:
    result
  changed_when: false
  failed_when: result.rc not in [0, 1]

- name: 起動時にSELinux無効化 (/etc/sysconfig/selinux)
  become: yes
  selinux: state=disabled
  when: result.rc == 0

- name: SELinux無効化 (setenforce)
  become: yes
  command: setenforce 0
  when: result.rc == 0

- name: firewalldが起動しているか確認
  become: yes
  shell: firewall-cmd --state
  register: firewall_state
  ignore_errors: yes
  changed_when: false
  check_mode: no

- name: firewalldでHTTPを許可
  become: yes
  command: firewall-cmd --zone=public --add-service=http --permanent
  when: firewall_state.rc == 0

- name: firewalldでgitbucketを作成
  become: yes
  command: firewall-cmd --permanent --new-service gitbucket
  when: firewall_state.rc == 0

- name: firewalldでgitbucketのssh portを作成
  become: yes
  command: firewall-cmd --permanent --service=gitbucket --add-port=29418/tcp
  when: firewall_state.rc == 0

- name: firewalldでgitbucketを許可
  become: yes
  command: firewall-cmd --zone=public --add-service=gitbucket --permanent
  when: firewall_state.rc == 0

- name: firewalldのポリシーをリロード
  become: yes
  command: firewall-cmd --reload
  when: firewall_state.rc == 0

- name: 開発ツールのインストール
  become: yes
  yum: name='@Development Tools'

- name: RubyとPassengerのビルドに必要な開発ツールやヘッダファイルのインストール
  become: yes
  yum:
    name='openssl-devel,readline-devel,zlib-devel,curl-devel,libyaml-devel,libffi-devel'

- name:  PostgreSQLとヘッダファイルのインストール
  become: yes
  yum:
    name='postgresql-server,postgresql-devel,python-psycopg2'

- name: Apacheとヘッダファイルのインストール
  become: yes
  yum:
    name='httpd,httpd-devel'

- name: ImageMagickとヘッダファイル・日本語フォントのインストール
  become: yes
  yum:
    name='ImageMagick,ImageMagick-devel,ipa-pgothic-fonts'

- name: curlのインストール
  become: yes
  yum:
    name='curl'

- name: yum Repository ius インストール
  become: yes
  shell:
    curl -s https://setup.ius.io | sh
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register:
    result_ius
  changed_when: false
  failed_when: result_ius.rc not in [0, 1]

- name: gitのアンインストール
  become: yes
  yum:
    name='git'
    state=absent

- name: gitのインストール
  become: yes
  yum:
    name='git2u'

- name: yum Repository wandisco インストール
  become: yes
  template:
    src=wandisco.repo
    dest=/etc/yum.repos.d/wandisco.repo
    force=no

- name: yum Repository wandisco key インストール
  rpm_key:
    key: "http://opensource.wandisco.com/RPM-GPG-KEY-WANdisco"

- name: subversion, mod_dav_svn のインストール
  become: yes
  yum: enablerepo=wandisco-svn
    name='subversion,mod_dav_svn'

- name: mod_dav_svnのコンフィグ削除
  file:
    path=/etc/httpd/conf.d/subversion.conf
    state=absent

- name: mod_perlのインストール
  become: yes
  yum:
    name='mod_perl'

- name: perl-DBIのインストール
  become: yes
  yum:
    name='perl-DBI'

- name: perl-DBD-pgのインストール
  become: yes
  yum:
    name='perl-DBD-Pg'

- name: perl-Digest-SHAのインストール
  become: yes
  yum:
    name='perl-Digest-SHA'

- name: javaのインストール
  become: yes
  yum:
    name='{{ java_version }}'

- name: そのほかのツールのインストール
  become: yes
  yum:
    name='which,wget'

- name: git ユーザ追加
  become: yes
  user:
    name=git
    shell=/bin/bash
    groups=apache
    createhome=yes
    home=/var/lib/git
    comment="Git repository"

- name: 作業ディレクトリ作成
  file: path={{ work_dir }}
    state=directory
    mode=0755
